### ISSUE TITLE
Hibernate 4 Compatibility

### ISSUE THREAD

**Issue by jdgiotta** [9ci/grails-quartz2#25]
Is this plugin compatible with hibernate 4? I recently upgraded to hibernate 4 on a very large system only discover at 4am that quartz 1.0.2 is not compatible.

**Comment by kefirfromperm** [comment]
grails-quartz 1.0.2 is compatible with hibernate4. If you have a trouble please create an issue in the grails-quartz repository.

**Comment by jdgiotta** [comment]
You're right, sorry. I was looking at an out of date Stackoverflow question:
http://stackoverflow.com/questions/17351952/which-grails-plugins-do-not-work-with-hibernate-4-plugin

**Comment by kefirfromperm** [comment]
https://github.com/kefirfromperm/grails-asynchronous-mail-sample
This is an example application demonstrates usage of my Asynchronous Mail plugin, which depends on quartz. Four branches demonstrate how to use hibernate3, hibernate4, mongodb and a cluster configuration.
